solved equation 568
furryurda/python-learning pull request #5
Opened 2023-02-20 18:24 UTC by furryurda

2023-02-20 20:03 UTC, FoxFurry requested changes
Немного изменений надо

2023-02-20 20:03 UTC, FoxFurry commented on peterson-5/equation-805.py
> +    print(f'(3+5)^2={(x+y)**z}'
Тут видимо по ошибке убрали скобочку `)` в конце строки. Код не будет запускаться без этой скобочки. Верни ее обрату и закоммить изменения.

2023-02-20 20:03 UTC, FoxFurry commented on peterson-5/equation-568.py
> +    print(f'{x+(y*z-a/(b-c))/m}')
Файл должен заканчиваться пустой строчкой. В конце 9 строчки добавь пустую строку

2023-02-21 16:18 UTC, furryurda commented on peterson-5/equation-805.py
> +    print(f'(3+5)^2={(x+y)**z}'
аа хорошо парастасная скобочка

2023-02-21 16:19 UTC, furryurda commented on peterson-5/equation-568.py
> +    print(f'{x+(y*z-a/(b-c))/m}')
ок

2023-02-21 16:25 UTC, furryurda commented on peterson-5/equation-568.py
> +    print(f'{x+(y*z-a/(b-c))/m}')
хм я вроде обновил и поставил 10 строчку и залил всё как надо а она не появляется

2023-02-21 18:49 UTC, furryurda commented on peterson-5/equation-568.py
> +    print(f'{x+(y*z-a/(b-c))/m}')
да блин она не появляется я опять обновил и поставил её

2023-02-21 19:45 UTC, FoxFurry approved these changes
Looks good!

2023-02-21 20:04 UTC, merged